### ISSUE TITLE
ibdata1 cannot be read. No valid checkpoint.

### ISSUE THREAD

**Issue by JorgenPhi** [KayoticSully/Mineshafter-Squared-Web#1]
I cannot get your ibdata1 file to open. I believe this is because the ib_logfile(#) files have not been uploaded. Could you pleases upload them? Thanks!

**Comment by KayoticSully** [comment]
Thanks for catching this btw, I've never synced a mysql database across github.  I was not sure what was needed.  Ideally the database should not be synced, but I'm lazy and did not want to figure out the best way to dump / recreate the database every time someone makes a change.
